export const PRACTICE_LESSON_BASE_MINUTES = 90;
export const PRACTICE_PROGRESS_CAP = 100;
export const PRACTICE_PRICE_PER_HOUR = 118;
export const PRACTICE_BASE_COST = 18;
export const PRACTICE_LOOP_RADIUS_KM = 4.5;
export const PRACTICE_ROUTE_POINT_DENSITY = 12;
export const HOME_ADDRESS_RADIUS_KM = 10;
export const HOME_ADDRESS_MAX_ATTEMPTS = 12;
